name: Build .exe using mingw + meson.

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install mingw, meson
        run: pacman -Syu --noconfirm meson cmake mingw-w64-headers mingw-w64-gcc git

      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Build
        run: meson setup --cross-file ${{github.workspace}}/x86_64-w64-mingw32.txt build && meson compile -C ${{github.workspace}}/build
