name: Build .exe using mingw + meson.

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Install mingw, meson
        run: pacman -Syu --noconfirm meson cmake mingw-w64-headers mingw-w64-gcc git clang

      - name: Checkout git repo, submodules
        run: git clone --recursive https://github.com/lunarlattice0/BR_ManagementTool.git
      
      - name: Build
        run: cd BR_ManagementTool && meson setup --cross-file x86_64-w64-mingw32.txt build && meson compile -C build

      - name: Export
        uses: actions/upload-artifact@v4
        with:
          name: blobs
          path: build/*
